version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      DB_HOST: "database"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    volumes:
      - .:/app
    ports:
      - "8080:8080"

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"